INSERT INTO SAMPLES (ID, NAME) VALUES (1, 'Main Test');
INSERT INTO SAMPLES (ID, NAME) VALUES (2, 'Main Test 2');
INSERT INTO SAMPLES (ID, NAME) VALUES (3, 'Main Test 3');
INSERT INTO SAMPLES (ID, NAME) VALUES (4, 'Main Test 4');
INSERT INTO SAMPLES (ID, NAME) VALUES (5, 'Main Test 5');
INSERT INTO SAMPLES (ID, NAME) VALUES (6, 'Main Test 6');
INSERT INTO SAMPLES (ID, NAME) VALUES (7, 'Main Test 7');
INSERT INTO SAMPLES (ID, NAME) VALUES (8, 'Main Test 8');
INSERT INTO SAMPLES (ID, NAME) VALUES (9, 'Main Test 9');